### ISSUE TITLE
Non Existent Code Repo

### ISSUE THREAD

**Issue by DeveloperOnCall** [amosmos/laravel-shopify#2]
This documentation references a composer item that does not exists.

Any idea where we get the working source?

**Comment by amosmos** [comment]
Which composer item that the documentation references does not exists?

**Comment by DeveloperOnCall** [comment]
composer require boaideas/laravel-shopify

**Comment by amosmos** [comment]
I don't understand. You type `composer require boaideas/laravel-shopify` and you get an error? And if so - what is the error you're getting? Can you paste it here?
