### ISSUE TITLE
Class RocketCode\Shopify\API does not exist

### ISSUE THREAD

**Issue by medspec** [amosmos/laravel-shopify#3]
installed via Composer

`
use RocketCode\Shopify\API as Shopify;

class ShopifyController extends Controller
{
	public function test(Shopify $shopify){

		$call = ShopifyAPI::call(
			[
				'URL' => 'products.json',
				'METHOD' => 'GET',
				'DATA' => [
					'limit' => 5,
					'published_status' => 'any'
				]
			]);

		return $call;
	}
}
`

Then i get the error
Class RocketCode\Shopify\API does not exist

**Comment by amosmos** [comment]
This package requires RocketCode's package so if you get an error saying the class doesn't exist you must have had an issue with the installation.

Also, on a different note, please note that you're using the Facade approach in your code, but still import and require the class in the dependency injection style.
