### ISSUE TITLE
ERROR #7: Failed to connect to https port 443: Timed out

### ISSUE THREAD

**Issue by ConduciveMammal** [amosmos/laravel-shopify#4]
So, I'm completely new to Laravel so this is likely something I've done or not done.

But when trying to load the page which this is suppost to work on, I receive this: `ERROR #7: Failed to connect to https port 443: Timed out`.

In web.php, I've added
```use RocketCode\Shopify\API as Shopify;

Route::get('/import', function (Shopify $shopify) {

    $call = $shopify->call(
    [
        'URL' => '/admin/products.json',
        'METHOD' => 'GET',
        'DATA' => [
            'limit' => 5,
            'published_status' => 'any'
        ]
    ]);
});```

I'm not sure if I've missed anything?

**Comment by amosmos** [comment]
From this error message it seems the problem is with the connection and not with the package... Are you sure you set the config parameters correctly plus opened your store for API access?
