### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by impactcolor** [amosmos/laravel-shopify#5]
Hi I'm getting a 404 error I've followed documentation and have setup my .env with this:

SHOPIFY_KEY=a3550blahblahblahblahblahblabh
SHOPIFY_SECRET=blahblahblahbaljsdlkfjaljsdf
SHOPIFY_DOMAIN=name.myshopify.com
SHOPIFY_TOKEN=blalblajsdlfiajslkdfjlaksjdfasdf

this gives me an error:
/vendor/rocket-code/shopify/src/RocketCode/Shopify/api.php

error is
"ERROR #22: The requested URL returned error: 400 Bad Request"

running laravel 5.6

THANK YOU!

**Comment by amosmos** [comment]
Hey, this error is from the RocketCode package and not this one... So you should ask there...

BUT, I do think it has to do with the code itself that your trying to run and not with the setup, and I believe it has to do with the endpoint you're trying to reach...

Hope this help!
Amos
